#!/usr/bin/perl -w

# developed from test-modem-calls by Chris Lenderman on March 25, 2010
# Created by Todd Andrews on September 9, 2014
# Last Modified by jlc on Sep 16, 2014
# Copyright 2010-2014
#
# This script simulates a TTY connection and sends CallerID data
# from a serial device to ncidd
# The way to test ncid and ncidd
# ./test-device-calls
# ./test-server ../server/ncidd -n1
# ../client/ncid 3334
#
use strict;
use IO::Socket;

#Open the testfile
my $testfile;
($testfile = shift) || ($testfile = "test-device-calls.data");
open(TESTFILE, $testfile) || die "Could not open $testfile\n";

#Obtain an ephemeral socket
my $temp_sock = socket(SOCK, AF_INET, SOCK_STREAM, 6 );
bind(SOCK, pack('S n a4 x8', AF_INET, 0, pack('C4', 127,0,0,1))) or die;
(my $port, my $tmp_addr) = sockaddr_in(getsockname(SOCK));
close (SOCK);

#Launch socat
system("socat PTY,link=./device0,raw,echo=0 TCP4-LISTEN:$port &");

sleep 2;

#Open a new socket based on the ephemeral port
my $BitMask=''; 
my $SocketAddress = pack('S n a4 x8', AF_INET, $port, pack('C4', 127,0,0,1)); 
socket(NEWSOCK, AF_INET, SOCK_STREAM, 6);
connect(NEWSOCK,$SocketAddress) || die "Could not establish socket connection.  Please ensure that the package \"socat\" is installed and that its path is included in \$PATH";
select(NEWSOCK); $| = 1;select(STDOUT);
vec($BitMask,fileno(NEWSOCK),1)=1;

#prompt for NCIDD connection
print "Connect server to port 3334 and tty ./device0 for test:\n";
print "    ./test-server ../server/ncidd -n1\n\n";
print "Then press <ENTER> multiple times to send different caller data\n\n";

#send the data
while (<TESTFILE>) {
    if (/^#\s+/) { next; }
	if (/^[#\w].*/) { $_ =~s/\\n/\n/g; print; print NEWSOCK; }
	else { my $response = <STDIN>; }
}

exit 0;
