#!/bin/sh
# postinst script for ncid server
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    configure)
        # configure NCID port if firewall installed and running
        if type firewall-cmd > /dev/null 2>&1
        then
            if firewall-cmd --quiet --state
            then
                if ! firewall-cmd --quiet --permanent --query-port=3333/tcp;
                then
                    firewall-cmd --quiet --permanent --add-port=3333/tcp
                fi
            fi
        fi 

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#update-rc.d ncidd defaults

exit 0
