#!/bin/sh
# prerm script for ncid client modules
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <prerm> `remove'
#        * <old-prerm> `upgrade' <new-version>
#        * <new-prerm> `failed-upgrade' <old-version>
#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
#        * <deconfigured's-prerm> `deconfigure' `in-favour'
#          <package-being-installed> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    remove|deconfigure)
        for script in /etc/init.d/ncid-*
        do
            if [ -f $script ]; then
                name=`basename $script`
                invoke-rc.d $name stop
                update-rc.d -f $name remove
            fi
        done
    ;;
    upgrade)
        # move any modules in old directory to new directory
        for i in /usr/share/ncid/ncid-*
        do
            if [ -f $i ]; then mv $i /usr/local/share/ncid/modules; fi
        done
    ;;
    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
